#!/bin/bash

# Setup script for Meant2Grow Firebase deployment
# This script helps set up environment variables and secrets

set -e

echo "🚀 Meant2Grow Deployment Setup"
echo "================================"
echo ""

# Determine environment
ENV="${1:-local}"

if [ "$ENV" != "local" ] && [ "$ENV" != "sandbox" ] && [ "$ENV" != "production" ]; then
    echo "Usage: $0 [local|sandbox|production]"
    echo ""
    echo "  local       - Set up local development environment (default)"
    echo "  sandbox      - Set up sandbox environment"
    echo "  production   - Set up production environment"
    exit 1
fi

ENV_FILE=".env.$ENV"
if [ "$ENV" = "local" ]; then
    ENV_FILE=".env.local"
fi

# Check if env file exists
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  $ENV_FILE already exists. Backing up to ${ENV_FILE}.backup"
    cp "$ENV_FILE" "${ENV_FILE}.backup"
fi

echo ""
echo "📝 Setting up $ENV environment"
echo "---------------------------------"
echo ""

# Set project-specific defaults
if [ "$ENV" = "production" ]; then
    DEFAULT_PROJECT_ID="meant2grow-prod"
    DEFAULT_AUTH_DOMAIN="meant2grow-prod.firebaseapp.com"
    DEFAULT_STORAGE_BUCKET="meant2grow-prod.appspot.com"
    DEFAULT_FUNCTIONS_URL="https://us-central1-meant2grow-prod.cloudfunctions.net"
    DEFAULT_APP_URL="https://meant2grow.com"
else
    DEFAULT_PROJECT_ID="meant2grow-dev"
    DEFAULT_AUTH_DOMAIN="meant2grow-dev.firebaseapp.com"
    DEFAULT_STORAGE_BUCKET="meant2grow-dev.appspot.com"
    DEFAULT_FUNCTIONS_URL="https://us-central1-meant2grow-dev.cloudfunctions.net"
    if [ "$ENV" = "sandbox" ]; then
        DEFAULT_APP_URL="https://sandbox.meant2grow.com"
    else
        DEFAULT_APP_URL="http://localhost:5173"
    fi
fi

echo "Please provide the following values (press Enter to use defaults):"
echo ""

read -p "Google OAuth Client ID: " GOOGLE_CLIENT_ID
read -p "Firebase API Key: " FIREBASE_API_KEY
read -p "Firebase Auth Domain [$DEFAULT_AUTH_DOMAIN]: " FIREBASE_AUTH_DOMAIN
FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN:-$DEFAULT_AUTH_DOMAIN}
read -p "Firebase Project ID [$DEFAULT_PROJECT_ID]: " FIREBASE_PROJECT_ID
FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-$DEFAULT_PROJECT_ID}
read -p "Firebase Storage Bucket [$DEFAULT_STORAGE_BUCKET]: " FIREBASE_STORAGE_BUCKET
FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET:-$DEFAULT_STORAGE_BUCKET}
read -p "Firebase Messaging Sender ID: " FIREBASE_SENDER_ID
read -p "Firebase App ID: " FIREBASE_APP_ID
read -p "Firebase VAPID Key (optional): " FIREBASE_VAPID_KEY
read -p "Functions URL [$DEFAULT_FUNCTIONS_URL]: " FUNCTIONS_URL
FUNCTIONS_URL=${FUNCTIONS_URL:-$DEFAULT_FUNCTIONS_URL}
read -p "App URL [$DEFAULT_APP_URL]: " APP_URL
APP_URL=${APP_URL:-$DEFAULT_APP_URL}

cat > "$ENV_FILE" << EOF
# $ENV Environment Configuration
# Generated by setup-env.sh on $(date)

# Google OAuth Client ID
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

# Firebase Config
VITE_FIREBASE_API_KEY=${FIREBASE_API_KEY}
VITE_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
VITE_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
VITE_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
VITE_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_SENDER_ID}
VITE_FIREBASE_APP_ID=${FIREBASE_APP_ID}
VITE_FIREBASE_VAPID_KEY=${FIREBASE_VAPID_KEY}

# Functions URL
VITE_FUNCTIONS_URL=${FUNCTIONS_URL}

# App URL
VITE_APP_URL=${APP_URL}
EOF

echo ""
echo "✅ Created $ENV_FILE file"
echo ""

if [ "$ENV" != "local" ]; then
    echo "📝 Step 2: Set Firebase Functions Secrets"
    echo "--------------------------------------------"
    echo ""
    echo "Which Firebase project should we configure secrets for?"
    read -p "Firebase project alias (sandbox/production) [$ENV]: " FIREBASE_ALIAS
    FIREBASE_ALIAS=${FIREBASE_ALIAS:-$ENV}
    
    echo ""
    echo "Switching to Firebase project: $FIREBASE_ALIAS"
    firebase use "$FIREBASE_ALIAS" || {
        echo "⚠️  Could not switch to $FIREBASE_ALIAS. Please run 'firebase use $FIREBASE_ALIAS' manually."
    }
    
    echo ""
    read -p "Service Account Email (e.g., meant2grow-meet-service@${FIREBASE_PROJECT_ID}.iam.gserviceaccount.com): " SERVICE_EMAIL
    echo ""
    echo "Please paste the service account private key (including BEGIN/END lines):"
    echo "Press Ctrl+D when done:"
    SERVICE_KEY=$(cat)
    
    echo ""
    echo "Setting secrets..."
    echo ""
    
    # Set secrets using Firebase CLI
    echo "$SERVICE_EMAIL" | firebase functions:secrets:set GOOGLE_SERVICE_ACCOUNT_EMAIL
    echo "$SERVICE_KEY" | firebase functions:secrets:set GOOGLE_SERVICE_ACCOUNT_KEY
    
    echo ""
    echo "✅ Secrets set for $FIREBASE_ALIAS project"
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
if [ "$ENV" != "local" ]; then
    echo "1. Deploy security rules: firebase deploy --only firestore:rules,storage:rules"
    echo "2. Build functions: cd functions && npm run build && cd .."
    echo "3. Build frontend: npm run build:$ENV"
    echo "4. Deploy: firebase deploy"
else
    echo "1. Start development server: npm run dev"
    echo "2. For deployment setup, run: ./setup-env.sh sandbox"
fi
echo ""


